name: Deploy Quartz
on:
  push:
    branches:
      - v4
  repository_dispatch:
    types: [notes_updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Engine
        uses: actions/checkout@v4

      - name: Clear and Create Content Folder
        run: |
          rm -rf content
          mkdir -p content

      - name: Fetch Notes
        uses: actions/checkout@v4
        with:
          repository: AdrianLazarski/quartz
          path: content
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & Build
        run: |
          npm install
          npx quartz build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages