name: Deploy Quartz
on:
  push:
    branches:
      - v4
  repository_dispatch:
    types: [notes_updated]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Engine
        uses: actions/checkout@v4

      - name: Clear and Create Content Folder
        run: |
          rm -rf content
          mkdir -p content

      - name: Fetch Notes
        uses: actions/checkout@v4
        with:
          repository: AdrianLazarski/quartz
          path: content
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & Build
        run: |
          npm install --force --legacy-peer-deps
          npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4